### ISSUE TITLE
:white_check_mark: 마이페이지 조립2 - 캐릭터 박스, 그래프 묶을 박스 및 전체 컨텐츠 묶을 wrapper 구현

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#114]
### Description

캐릭터 박스, 그래프 묶을 박스 및 전체 컨텐츠 묶을 wrapper를 구현합니다

### To-do

- [x] 캐릭터 박스와 그래프를 묶을 박스 구현
  - [x] grid로 데스크탑 사이즈에서는 가로 병렬 배치, 모바일에서는 세로 병렬 배치
  - [x] 각 박스 size 및 여백 조절  
- [x] 컨텐츠 wrapper 구현
  - [x] 좌우 padding으로 디자인 시안대로 여백 조절
  - [x] width, height 조정
  - [x] 컨텐츠박스 별 여백 조정
  - [x] 하위 박스에서 받아야 할 prop 전달
