### ISSUE TITLE
:bug: 제목 그래프 setter props 타입 및 infinite depth 버그

### ISSUE THREAD

**Issue by shyjnnn** [najasin/na-jasin-fe#128]
### Description
<img width="460" alt="image" src="https://github.com/najasin/na-jasin-fe/assets/81355590/65d64909-a611-4179-872d-d3b70a834b95">

### To-do

- [ ] type 재설정 (button type 지정하는 것도)
- [ ] 하나의 객체 안에 { 키워드: number, 키워드: number, ... }
- [ ] 넘겨주는 핸들러 형식  ({ key: value }) => { setter({ key: value }) }
- [ ] recoil type으로 바꿨을 경우, infinite depth 버그 해결
![image](https://github.com/najasin/na-jasin-fe/assets/129242822/3f2edf9d-725b-402f-bb2a-c2da177afb1e)
