### ISSUE TITLE
:bug: 마이페이지 일부 오류 수정

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#169]
### Description

마이페이지의 일부 오류를 수정합니다

### To-do

- [ ] 페이지 server component로 수정
- [ ] 기타 하위 컴포넌트 client component로 수정
- [ ] data fetch -> refresh 해서 항상 새로운 데이터 받아올 수 있도록(현재는 처음에만 데이터 불러오고 끝)
