### ISSUE TITLE
:white_check_mark: 미들웨어 기능 구현 명세

### ISSUE THREAD

**Issue by wooleejaan** [najasin/na-jasin-fe#179]
### Description

next js 13 middleware 기능 추가 구현 

### To-do

- [x] #192
  - 로그인을 했는데 다시 홈페이지로 왔을 경우, 
  - userType ""이면 등록하기 페이지로 이동 (이후 타입추가되면 모달 페이지 => 등록하기 페이지로) 
  - userType 존재하면 등록하기가 아니라 마이페이지로 (jff/mypage?userId)  
  - 로그아웃 시 userId, userType 도 추가적으로 제거
 
- [x] #196
  - 등록 완료 시 유저 타입 쿠키에 저장 필요 
  - 토큰이 없는데 접근 시 홈페이지로 redirect 
  - 토큰은 있지만, userType이 이미 존재하는 경우? => ?? 등록하기 반복 가능? 아니면 막기? 

- [ ] 마이페이지는 접근 가능?
  - 등록한 유저타입이라면 가능하게 하고, 등록하지 않은 유저 타입이라면 등록하기로 라우팅하기 

- [ ] 각 페이지 단위 토큰 검증 (userId, token payload 비교 로직 구상)

- [ ] 유저타입에 따른 라우팅 처리 추가 구현 
  - 최신 유저 타입 받으면 곧이 곧대로 라우팅 이후 각 페이지에서 등록한 유저 목록 처리

- [ ] 기타 
  - 서버 컴포넌트 쿠키 주입 가능 여부 확인 
  - 미들웨어에서 query string 처리하기 때문에 괜찮은건지 체크

현재 등록한 유저 타입 목록 갱신 주체 
- 등록하기, 마이페이지 (get 해와서 쿠키에 저장) 
  - 각 페이지 별로 유저 타입 리스트 받아서 저장까지는 해야. 
  - 미들웨어에서는 userId, 토큰 등으로만 redirect 처리하고, 유저타입은 open 
  - 유저타입 안 맞는 건 각 페이지 별로 라우팅 핸들링해야 한다.

홈페이지
- userType이 없으면 기본 jff/my-manual로 redirect (미들웨어)
- userType이 있으면 {userType}/my-page?userId={userId}로 redirect (미들웨어)

등록하기 페이지 
- 토큰이 없으면 홈페이지로 redirect 
- 등록 완료 시, {userType}/my-page?userId={userId} 로 클라이언트에서 처리 (본인 path의 userType을 보고 있는다) 
- 유저리스트에 "있는"데, 이 등록하기로 오려고 하면 {userType}/my-page?userId={userId}로 redirect (미들웨어)

마이 페이지
- 토큰 없어도 접근 가능 (미들웨어)
- 대신 userId={userId} 라는 쿼리 스트링이 없으면 홈페이지로 redirect (미들웨어)
- 클라이언트 측에서 유저타입 목록에 없는 곳으로 왔을 경우 처리해줘야 한다..? 
- userId도 있는데, 쿠키에 있는 유저 리스트에 "없는" 경우, => 타인일 수 있다. 
- 나머지는 클라이언트에서 처리 나면 편집 보여주고 아니면 편집 안 보여주고 

타적나사 페이지 
- 토큰 없어도 접근 가능 (미들웨어)
- userId가 안 붙어 있으면 redirect 
- userId도 있는데, 쿠키에 있는 유저 리스트에 "없는" 경우, => 타인일 수 있다. 당연 타적나사니까.  
- 클라이언트에서 처리해야 할 게, 유저 목록을 받아서, 없는 타입으로 온 경우 클라이언트에서 redirect 처리해줘야 한다 (클라이언트) 
- 왜냐면 여기는 쿠키로 미리 알 수 없어서 
- 클라이언트 쪽에서 userId, userType 요청 해보고 없는 경우를 에러 핸들링 해야 한다. 

그 외에는 그냥 미들웨어에서 위 예외사항을 제외한 경우, 즉 가능한 경우 userType을 쿠키에 미들웨어가 업데이트
