### ISSUE TITLE
:factory: API 수정 사항 반영

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#205]
### Description

API 수정 소요가 있어 해당 수정 내용을 마이페이지 전반 코드에 반영합니다.

### To-do
- [x] #213
- [x] #211
  - [x] API response type 수정
  - [x] ProfileBox prop type 수정
    - [x] othersKeywordPercents
    - [x] myKeywordPercents
  - [x] RadarChartContainer prop type 수정
    - [x] OthersKeywordPercents
  - [x] RadarChart
