### ISSUE TITLE
:white_check_mark: FAB 내 원형 버튼 UI 구현

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#21]
### Description

FAB 버튼에서 사용되는 원형 버튼 UI를 구현합니다.

### To-do

- [x] 원형 버튼 UI 구현
- [x] size prop 설정
- [x] 내부 image prop 설정
- [x] bg-color prop 설정
