### ISSUE TITLE
:bug: 전체 공통 컴포넌트 스타일 수정

### ISSUE THREAD

**Issue by shyjnnn** [najasin/na-jasin-fe#228]
### Description
- 마이페이지 inventory 모달 및 manual 모달, width, heiht이 현재 반응형 안됩니다

### To-do

- [ ]  my page manual modal 반응형 적용
- [ ] my page inventory modal 반응형 적용
- [ ] my page characterbox mobile일때 보이게하기
