### ISSUE TITLE
:bug: 마이페이지 편집 모달(캐릭터, 설명서) 레이아웃 수정

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#261]
### Description

마이페이지의 편집 모달 2개의 레이아웃을 수정합니다.

### To-do

- [x] 캐릭터 편집 모달
  - [x] 내부 content 영역 높이가 줄어들었을 때 튀어 나오는 문제
  - [x] CharacterBox와 Inventory가 중앙 정렬 되지 않는 문제 
- [x] 설명서 편집 모달
  - [x] 내부 content 영역 높이가 줄어들었을 때 튀어 나오는 문제
