### ISSUE TITLE
:factory: FAB, CircleButton shareUrl 만드는 로직 중복 문제 리팩토링

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#279]
### Description

FAB, CircleButton shareUrl 만드는 로직 중복 문제 리팩토링

### To-do

- [x] FAB에서 shareUrl 정의 후 prop으로 내려주기
- [x] CircleButton prop type 수정
- [x] shareUrl 제대로 생성되었을 경우만 kakao initialize 되는 로직 추가
