### ISSUE TITLE
:white_check_mark: 마이페이지 get/put API 에러 처리

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#296]
### Description

마이페이지 get/put API 에러 처리를 합니다.

### To-do

- [x] `GET`
  - [x] userId가 유효하지 않은 경우
  - [x] userType이 유효하지 않은 경우
- [ ] `PUT`
  - [ ] token이 잘못된 경우
