### ISSUE TITLE
:white_check_mark: config - tanstack query/axios/msw 초기 세팅, 기본 font 적용/meta data 추가

### ISSUE THREAD

**Issue by wooleejaan** [najasin/na-jasin-fe#45]
### Description

설명을 입력해 주세요

### To-do

- [ ] tanstack query 세팅
- [ ] axios 세팅 
- [ ] msw 세팅 
- [ ] 기본 font 적용 
- [ ] meta data 추가
