### ISSUE TITLE
:white_check_mark: 설명서 개별 카드(기본 / 꿀팁) UI 구현

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#64]
### Description

마이페이지 내에 삽입될 카드 UI를 구현합니다.

### To-do

- [x] 기본 카드 UI 구현
- [x] 꿀팁 카드 UI 구현
  - [x] 타인이 작성하므로 닉네임 칩 필요
