### ISSUE TITLE
:white_check_mark: Fab 컴포넌트 모바일 포지셔닝 구현

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#70]
### Description

Fab 컴포넌트 내의 circleButton들이 모바일 화면에서 배치되는 위치를 구현합니다. 

### To-do

- [x] mobile position 구현
- [x] base button 위치 및 애니메이션 수정 (버튼 사이즈가 작아지니 위치 때문에 문제가 생기는 듯...)
- [x] base 버튼 색상 변경 : blue-point
- [x] 링크 버튼 색상 변경 : black
- [x] 꿀팁받기 버튼 border, font 색상 변경 : blue-point
