### ISSUE TITLE
:factory: DescriptionCard 컴포넌트 수정

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#75]
### Description

디자인 변경에 따라 DescriptionCard 컴포넌트를 수정합니다.

### To-do

- [x] '기본' case에서는 답변 한 줄이 card 하나에 배치되도록
- [x] '꿀팁' case에서는 타인이 작성한 2가지 응답이 card 하나에 배치되고, 닉네임 chip이 달릴 수 있도록
- [x] 각각 따로 구현하는 편이 나을 수도 있을 것 같습니다.
