### ISSUE TITLE
:white_check_mark: DescriptionCard 컴포넌트 모바일 반응형 구현

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#76]
### Description

DescriptionCard 컴포넌트 모바일 반응형 구현

### To-do

- [x] MyDescriptionCard 모바일 반응형 구현
  - [x] 문장이 자연스럽게 넘어가는지 확인
  - [x] width를 고정하지 않고 부모 컴포넌트에 100% 찰 수 있도록 구현
  - [x] padding 조절
  - [x] border-radius 조절
- [ ] OthersDescriptionCard 모바일 반응형 구현
  - [x] 문장이 자연스럽게 넘어가는지 확인
  - [x] width를 고정하지 않고 부모 컴포넌트에 100% 찰 수 있도록 구현
  - [x] padding 조절
  - [x] border-radius 조절
  - [ ] chip 배치 고려해야 함 (absolute 포지션으로 두었는데, 문장이 길어지면 chip과 문장이 겹치는 문제 발생)
