### ISSUE TITLE
:white_check_mark: 마이페이지 조립1 - 제목, ForDev 버튼

### ISSUE THREAD

**Issue by Andy-Shin99** [najasin/na-jasin-fe#94]
### Description
마이페이지 조립을 시작합니다.

### To-do

- [x] ForDev 버튼 제작
- [x] 제목, ForDev 버튼 레이아웃 잡기
- [ ] 각 캐릭터, 그래프, 설명서 박스 레이아웃 잡기
